lsi: false
highlighter: rouge
safe: true
markdown: kramdown

# top navigation links
navigation:
- text: Home
  url: /index.html
- text: Open Source
  url: /open-source.html
- text: Contact
  url: /contact.html
